<a href="https://colab.research.google.com/github/LemonSqu33zy/MAT421/blob/main/Module_D_Section_1_1%2C_1_2%2C_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
## Dot product is an important part of linear algebra. This code is just an
## example of coding such a function in python.
import numpy as np

X = [2,4]
Y = [3,9]

print("The dot product of [2,4] and [3,9] is",np.dot(X,Y))

The dot product of [2,4] and [3,9] is 42


In [5]:
## We find an orthogonal matrix by implementing a qr factorization. This can in 
## theory generate orthonormal vectors, as you can find the norm and pairwise
## orthogonality. 
import numpy as np
from scipy.linalg import qr

X = np.random.randn(5,5)
Y,Z = qr(X)
print("The matrix is:")
print(X)
print("The orthogonal matrix is:")
print(Y.dot(Y.T))

The matrix is:
[[ 0.86563447  0.89806737  0.86318515  1.10221027  0.98284694]
 [-1.41137361 -0.82709246 -1.3972254   0.38811316 -1.73169835]
 [ 0.06918993  1.61250603  1.72360387  0.35276978 -0.73980753]
 [-0.58654043  2.302484    0.42659152 -0.49878604  0.79193518]
 [ 1.5786527  -1.18827197  1.2124903  -0.48069097 -0.32700725]]
The orthogonal matrix is:
[[ 1.00000000e+00  3.69261644e-16  5.21257348e-17  3.93763445e-18
   2.15549912e-16]
 [ 3.69261644e-16  1.00000000e+00 -5.70046052e-17 -1.49736597e-17
   8.56478927e-17]
 [ 5.21257348e-17 -5.70046052e-17  1.00000000e+00 -2.33904032e-17
  -3.33635305e-17]
 [ 3.93763445e-18 -1.49736597e-17 -2.33904032e-17  1.00000000e+00
  -4.14255322e-17]
 [ 2.15549912e-16  8.56478927e-17 -3.33635305e-17 -4.14255322e-17
   1.00000000e+00]]


In [12]:
## We use the eig function in linalg to find the eigenvalues and eigenvectors. 
## An eigenvalue is a value such that when the eigenvector is multiplied by the 
## matrix, it is equal to the eignvalue multiplied by the eigenvector. 
import numpy as np
from scipy.linalg import eig

X = np.random.randn(2,2)
Y = eig(X)
print("With the matrix:")
print(X)
print("The eignevalues and eigenvectors are:")
print(Y)


With the matrix:
[[-1.05104735 -0.15594798]
 [-0.32795652 -0.39817334]]
The eignevalues and eigenvectors are:
(array([-1.12173158+0.j, -0.32748911+0.j]), array([[-0.91080867,  0.21069122],
       [-0.41282875, -0.97755266]]))
